### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ovninosa** [MahmoudMohamedIsmail/speaker-recognition-identification-system#1]
Hello, few days a go I downloaded your code, when I run it and try to test the verification the app crash. Do you have any idea on this? Or if you can upgrade the code will be amazing.
Thanks.

**Comment by MahmoudMohamedIsmail** [comment]
Hello.
Sorry for late.

FIRST: Pre-requisites
1. ```
     Install the MATLAB Compiler Runtime 2012a on your computer
   ```
2. ```
     Restart the computer
   ```
3. ```
     Open the template C# code
   ```
   
   Note:This version of code is tried and worked under 64-bit Windows7 OS.

If there are problems or Erorrs , text me.
Thanks in advance.

On 11 July 2016 at 23:59, javenosa notifications@github.com wrote:

> Hello, few days a go I downloaded your code, when I run it and try to test
> the verification the app crash. Do you have any idea on this? Or if you can
> upgrade the code will be amazing.
> Thanks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/MahmoudMohamedIsmail/speaker-recognition-identification-system/issues/1,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQXh0jIqmwMeDKBTnAS3gGvy04__7gvNks5qUrzYgaJpZM4JJ07g
> .

**Comment by ovninosa** [comment]
I already have installed the runtime 2012a.

If I run the app and open a wav file throw this exception over recorder.exe:
**System.TypeInitializationException Recorder.exe**
Over this method:

```
public static Sequence ExtractFeatures(AudioSignal signal)
{
    return MFCC.MFCC.ExtractFeatures(signal.data, signal.sampleRate);
}
```

If I run the app and enter a random name and push "compare" the app crash with the following exception:
**System.IO.DirectoryNotFoundException mscorlib.dll**
On this method:
**static private List<User> LoadDataset(string datasetFileName)**
On this specific line:
**StreamReader reader = new StreamReader(datasetFileName);**

**The program look this file "TestingList.txt" over this path (of course this path only exist on your PC):
E:\programing education\ain shams stage 3\just year\algorithm\labs\PROJECT RELEASE (1)\Startup Codes\Speaker Identification Startup Code\Speaker Identification Startup Code\Complete SpeakerID Dataset\TestingList.txt**

Thanks for your time.
Javenosa

**Comment by ovninosa** [comment]
@MahmoudMohamedIsmail Any news on this?
Thanks
